ALTER TABLE ADDRESS
ADD CONSTRAINT unique_places
   UNIQUE (CITY,STREET,BUILDING_NUMBER,FLAT_NUMBER);

ALTER TABLE EMPLOYEE
DROP CONSTRAINT SYS_C00602414;

ALTER TABLE EMPLOYEE
ADD CONSTRAINT pesel_check
   FOREIGN KEY (PESEL)
   REFERENCES PERSON (PESEL) 
   initially deferred deferrable;
   
ALTER TABLE PERSON
DROP CONSTRAINT SYS_C00602369;

ALTER TABLE PERSON
ADD CONSTRAINT address_check
   FOREIGN KEY (ID_addr)
   REFERENCES ADDRESS (ID_addr) 
   initially deferred deferrable;