DROP TABLE ADDRESS;
DROP TABLE BRANCH;
DROP TABLE BURIAL;
DROP TABLE CEMETERY;
DROP TABLE COFFIN;
DROP TABLE CUSTOMER;
DROP TABLE EMPLOYEE;
DROP TABLE FLORALTRIBUTE;
DROP TABLE PERSON;
DROP TABLE POSITION;
DROP TABLE TAKE_PART;
DROP TABLE SALARY_OR_BONUS;

DROP SEQUENCE CUSTOMER_ID_CUSTOMER_SEQ;
DROP SEQUENCE EMPLOYEE_ID_EMPLOYEE_SEQ;
DROP SEQUENCE ADDRESS_ID_ADDR_SEQ;