CREATE SEQUENCE address_ID_addr_seq START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE customer_ID_customer_seq START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE employee_ID_employee_seq START WITH 1 NOCACHE ORDER;